services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  macaco-maluco:
    image: macacomaluco/macaco-maluco
    environment:
      - VIRTUAL_HOST=macacomaluco.space
      - VIRTUAL_PORT=80
    expose:
      - 80

  pressora:
    image: macacomaluco/pressora
    environment:
      - VIRTUAL_HOST=pressora.macacomaluco.space
      - VIRTUAL_PORT=80
    expose:
      - 80

  unbubble:
    image: pirelenito/unbubble
    environment:
      - VIRTUAL_HOST=unbubble.space
      - VIRTUAL_PORT=80
    expose:
      - 80

  birinto:
    image: macacomaluco/birinto
    environment:
      - VIRTUAL_HOST=birinto.macacomaluco.space
      - VIRTUAL_PORT=80
    expose:
      - 80

  go-horse-go:
    image: macacomaluco/go-horse-go
    environment:
      - VIRTUAL_HOST=go-horse-go.macacomaluco.space
      - VIRTUAL_PORT=80
    expose:
      - 80

  cinema-fu:
    image: macacomaluco/cinema-fu
    environment:
      - TMDB_API_KEY
      - MONGO_PORT=tcp://mongo:27017
      - MONGO_DATABASE=cinema-fu
      - VIRTUAL_HOST=cinema-fu.macacomaluco.space
      - VIRTUAL_PORT=80
    expose:
      - 80
    links:
      - mongo

  mongo:
    image: mongo:2.4.14
    expose:
      - 27017

  # redis:
  #   image: redis
